# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z33-nOToyLmhxMekdtynnxRcdDpaFm1E
"""

x=int(input('enter first value:'))
 y=int(input('enter second value:'))
 print('power:' ,x**y)

x=int(input('enter first value:'))
 y=int(input('enter second value:'))
 pow(x,y)

